sonar.projectKey=kanashii00_pedalyaV2
sonar.organization=kanashii00
sonar.projectName=pedalyaV2

sonar.sources=app,resources
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=**/vendor/**,**/storage/**,**/bootstrap/cache/**,**/node_modules/**,**/*.blade.php

sonar.sourceEncoding=UTF-8
